const { chromium }=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert=require('node:assert/strict');const fs=require('node:fs');fs.mkdirSync('test-results',{recursive:true});
(async()=>{
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=swiftshader','--enable-webgl','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1440,height:900}});const errors=[],failures=[],checks=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('response',r=>{if(r.status()>=400)failures.push({url:r.url(),status:r.status()})});
await page.goto('http://127.0.0.1:5173/?test=1');await page.waitForFunction(()=>window.__abyss);await page.screenshot({path:'test-results/menu.png'});
await page.getByRole('button',{name:'Begin dive'}).click();await page.waitForFunction(()=>!!document.pointerLockElement);checks.push('Begin dive acquires native pointer lock');
await page.mouse.move(720,450);await page.evaluate(()=>{const w=window.__abyss;w.targetYaw=w.yaw=0;w.targetPitch=w.pitch=0;});await page.mouse.move(800,450);await page.waitForTimeout(350);
const camera=await page.evaluate(()=>{const w=window.__abyss;return {yaw:w.yaw,x:w.camera.getWorldDirection(w.forward).x};});assert.ok(camera.yaw<0&&camera.x>0);checks.push('Native rightward mouse motion turns camera right without dragging');
await page.evaluate(()=>{const w=window.__abyss;w.yaw=w.targetYaw=0;});const before=await page.evaluate(()=>window.__abyss.mission.position.z);await page.keyboard.down('w');await page.waitForTimeout(900);await page.keyboard.up('w');assert.ok(await page.evaluate(()=>window.__abyss.mission.position.z)<before);checks.push('Native WASD input moves the player');
await page.keyboard.press('f');assert.equal(await page.evaluate(()=>window.__abyss.mission.torch),false);await page.keyboard.press('f');checks.push('F switches torch off and on');
await page.screenshot({path:'test-results/entrance.png'});
await page.keyboard.press('Escape');await page.waitForFunction(()=>!window.__abyss.playing);const paused=await page.evaluate(()=>window.__abyss.mission.elapsed);await page.waitForTimeout(350);assert.equal(await page.evaluate(()=>window.__abyss.mission.elapsed),paused);checks.push('Escape releases pointer and freezes mission time');await page.getByRole('button',{name:'Resume dive'}).click();
await page.evaluate(()=>{const w=window.__abyss;w.mission.position={x:24,y:3,z:-65};w.position.copy(w.mission.position);w.mission.predator.position={x:22,y:3,z:-78};w.mission.predator.state='alert';w.mission.predator.timer=0;w.yaw=w.targetYaw=0;w.pitch=w.targetPitch=0;w.velocity.set(0,0,0);});await page.waitForTimeout(500);await page.screenshot({path:'test-results/guardian.png'});
await page.evaluate(()=>{const w=window.__abyss;w.mission.position={x:0,y:3,z:-110};w.position.copy(w.mission.position);w.mission.predator.position={x:20,y:3,z:-64};w.velocity.set(0,0,0);w.yaw=w.targetYaw=0;w.pitch=w.targetPitch=-.2;});await page.waitForTimeout(300);await page.keyboard.press('e');assert.equal(await page.evaluate(()=>window.__abyss.mission.pending),1);await page.screenshot({path:'test-results/swap.png'});await page.keyboard.press('2');await page.keyboard.press('e');assert.equal(await page.evaluate(()=>window.__abyss.mission.inventory[1]),'relic');assert.ok(await page.evaluate(()=>window.__abyss.mission.pickups.some(p=>p.item==='wood')));checks.push('E / 2 / E swaps relic into full inventory and drops displaced wood');
await page.evaluate(()=>{const w=window.__abyss;w.mission.position={x:32,y:3,z:-12};w.position.copy(w.mission.position);w.velocity.set(0,0,0);w.pitch=w.targetPitch=-.3;});await page.waitForTimeout(300);await page.screenshot({path:'test-results/extraction.png'});await page.keyboard.press('e');await page.getByRole('button',{name:'Try another dive'}).waitFor();assert.equal(await page.evaluate(()=>window.__abyss.mission.outcome),'won');await page.screenshot({path:'test-results/win.png'});checks.push('Extraction with relic displays win and releases pointer');
await page.getByRole('button',{name:'Try another dive'}).click();assert.deepEqual(await page.evaluate(()=>({air:Math.ceil(window.__abyss.mission.air),health:window.__abyss.mission.health,relic:window.__abyss.mission.hasRelic,slots:window.__abyss.mission.inventory.length})),{air:27,health:100,relic:false,slots:5});checks.push('Restart restores player, air, health, inventory and objective');
await page.evaluate(()=>window.__abyss.mission.air=.001);await page.getByRole('button',{name:'Try another dive'}).waitFor();assert.equal(await page.evaluate(()=>window.__abyss.mission.outcome),'lost');await page.screenshot({path:'test-results/loss.png'});checks.push('Air depletion displays lose and restart flow');
const renderer=await page.evaluate(()=>({calls:window.__abyss.renderer.info.render.calls,triangles:window.__abyss.renderer.info.render.triangles,programCount:window.__abyss.renderer.info.programs.length,webglVersion:window.__abyss.renderer.getContext().getParameter(window.__abyss.renderer.getContext().VERSION)}));
// Dedicated fallback page: browser refuses pointer lock, movement must still look.
const fallback=await browser.newPage({viewport:{width:1100,height:760}});await fallback.addInitScript(()=>{HTMLCanvasElement.prototype.requestPointerLock=function(){return Promise.reject(new Error('Denied for fallback test'));};});await fallback.goto('http://127.0.0.1:5173/?test=1');await fallback.waitForFunction(()=>window.__abyss);await fallback.getByRole('button',{name:'Begin dive'}).click();await fallback.mouse.move(600,450);const fallbackYaw=await fallback.evaluate(()=>window.__abyss.targetYaw);await fallback.mouse.move(650,450);assert.ok(await fallback.evaluate(()=>window.__abyss.targetYaw)<fallbackYaw);checks.push('Denied pointer lock falls back to mouse look without click-drag');
const wheel=await fallback.evaluate(()=>{const w=window.__abyss,b=w.targetYaw;w.renderer.domElement.dispatchEvent(new WheelEvent('wheel',{deltaX:80,cancelable:true}));return {before:b,after:w.targetYaw,selected:w.mission.selected};});assert.ok(wheel.after<wheel.before);assert.equal(wheel.selected,0);checks.push('Horizontal trackpad scroll turns right; wheel does not change hotbar');
await fallback.keyboard.press('Escape');await fallback.getByRole('button',{name:'Resume dive'}).waitFor();await fallback.screenshot({path:'test-results/menu-1100.png'});
assert.deepEqual(failures,[]);assert.deepEqual(errors,[]);checks.push('No browser runtime, shader compilation or HTTP resource errors');
const report={browser:await browser.version(),rendering:'Real WebGL 2 renderer using SwiftShader (software GPU)',checks,renderer,camera,errors,failures,note:'Browser scenarios use test-only position/state setup for encounters and endings. The separate full-route simulation traverses collision and live AI without teleportation. Physical trackpad and native GPU performance are not manually verified.'};
fs.writeFileSync('test-results/browser-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
